### ISSUE TITLE
Doesn't work, throws exception

### ISSUE THREAD

**Issue by dsmid** [dhaltmayer/ZoomR#1]
Doesn't work on Chrome 40.0.2214.111 (64-bit, Linux).
Throws exceptions:

TypeError: undefined is not a function
    at chrome-extension://jgmpfcpmgehgmeodlemlnnbpcdokboca/background.js:22:14

TypeError: undefined is not a function
    at chrome-extension://jgmpfcpmgehgmeodlemlnnbpcdokboca/background.js:5:15

Method getZoom() seems to be undefined.

**Comment by dsmid** [comment]
I suppose you need to provide tabId as the first parameter since version 38.
https://developer.chrome.com/extensions/tabs#method-getZoom

**Comment by dhaltmayer** [comment]
Thanks. I honestly haven't used/tested it in a while, so that makes sense.

**Comment by dhaltmayer** [comment]
I wonder if this is Linux-specific, because it still works just fine for me, on Mac OS.
